[Tellstick] Fix for issue #3849 (#4231)
* The root-cause for the problem was that the included javatellstick library did not handle callbacks from the telldus core library in correct way,
hence when OH2.4 included a newer version of the jna-library (v.4.5.2) the binding stopped working with an exception thrown:
 java.lang.IllegalArgumentException: Invalid calling convention 63.

A problem was then discovered as the binding maintainer did not have the complete source code for the javatellstick library due to a HDD crash,
I therfor decompiled the source code from the original javatellstick-1.0.jar. I've added all decompiled code changes and built a new version of the library called javatellstick-1.1.jar.
I've also changed a typo in the naming of one of the class files.
The complete source code for javatellstick can be found [here](https://github.com/jannegpriv/javatellstick).

Signed-off-by: Jan Gustafsson <jannegpriv@gmail.com> (github: jannegpriv)
Signed-off-by: Pascal Larin <plarin@gmail.com>